version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jairperrut/shopping_cart:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: make run-server

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: jairperrut/shopping_cart:latest
    command: make run-tests
